### ISSUE TITLE
"read_from_binary()" function fails when using a .BIN file from PyRecastDetour.

### ISSUE THREAD

**Issue by PrivateCaller** [Tugcga/Path-Finder#2]
I'm trying to use a .BIN file outputted from PyRecastDetour with Pynavmesh, but trying to use the ```read_from_binary``` functions outputs the following error:
```  
File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pathfinder\__init__.py", line 44, in read_from_binary
    value = struct.unpack(">f", bs)[0]
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by Tugcga** [comment]
`read_from_binary` method is not compatible win *.bin files from RecastDetour. It read binary files, outputted from `baker.save_to_binary` method. These binary files are very similar to simple txt-files with three arrays inside it (vertex positions, polygon corner indices and polygon sizes), but encoded in binary form instead of text format. The structure of RecastDetour *.bin files are more complicated, and I don't understand it.
